<?php

namespace App\Http\Controllers\Guru;

use App\Http\Controllers\Controller;
use App\Models\{Absensi, JadwalMengajar, QrCode, Guru};
use App\Services\ValidationService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

class AbsensiController extends Controller
{
    protected $validationService;

    public function __construct(ValidationService $validationService)
    {
        $this->validationService = $validationService;
    }

    // Get coordinates from config
    protected function getSchoolCoordinates()
    {
        return [
            'lat' => config('gps.school_latitude', -6.200000),
            'lng' => config('gps.school_longitude', 106.816666),
            'radius' => config('gps.radius_meters', 200),
        ];
    }

    /**
     * Halaman Scan QR Code (Guru scan QR dari Ketua Kelas)
     */
    public function scanQr()
    {
        $user = Auth::user();
        $guru = $user->guru;

        if (!$guru) {
            return redirect()->route('guru.dashboard')
                ->with('error', 'Data guru tidak ditemukan.');
        }

        // Ambil jadwal hari ini yang belum diabsen
        $hari_ini = ucfirst(Carbon::now()->locale('id')->dayName);
        $jadwal_hari_ini = JadwalMengajar::where('guru_id', $guru->id)
            ->where('hari', $hari_ini)
            
            ->whereDoesntHave('absensi', function($q) {
                $q->whereDate('tanggal', Carbon::today());
            })
            ->with(['kelas', 'mataPelajaran'])
            ->orderBy('jam_mulai')
            ->get();

        return view('guru.absensi.scan-qr', [
            'guru' => $guru,
            'jadwal_hari_ini' => $jadwal_hari_ini,
            'koordinat_sekolah' => $this->getSchoolCoordinates(),
        ]);
    }

    /**
     * Halaman Absensi Selfie
     */
    public function selfie()
    {
        $user = Auth::user();
        $guru = $user->guru;

        if (!$guru) {
            return redirect()->route('guru.dashboard')
                ->with('error', 'Data guru tidak ditemukan.');
        }

        // Ambil jadwal hari ini yang belum diabsen
        $hari_ini = ucfirst(Carbon::now()->locale('id')->dayName);
        $jadwal_hari_ini = JadwalMengajar::where('guru_id', $guru->id)
            ->where('hari', $hari_ini)
            
            ->whereDoesntHave('absensi', function($q) {
                $q->whereDate('tanggal', Carbon::today());
            })
            ->with(['kelas', 'mataPelajaran'])
            ->orderBy('jam_mulai')
            ->get();

        return view('guru.absensi.selfie', [
            'guru' => $guru,
            'jadwal_hari_ini' => $jadwal_hari_ini,
            'koordinat_sekolah' => $this->getSchoolCoordinates(),
        ]);
    }

    /**
     * Proses Absensi via QR Code
     * QR Code divalidasi dari database qr_codes (generated by Ketua Kelas)
     */
    public function prosesAbsensiQr(Request $request)
    {
        try {
            $request->validate([
                'qr_data' => 'required|string',
                'latitude' => 'required|numeric',
                'longitude' => 'required|numeric',
            ]);

            $user = Auth::user();
            $guru = $user->guru;

            if (!$guru) {
                return response()->json([
                    'success' => false,
                    'message' => 'Data guru tidak ditemukan.',
                ], 404);
            }

            // 1. VALIDASI QR CODE dari Database (bukan decode JSON)
            $qr_code = QrCode::where('qr_data', $request->qr_data)
                ->where('is_used', false)
                ->first();

            if (!$qr_code) {
                return response()->json([
                    'success' => false,
                    'message' => 'QR Code tidak valid atau sudah digunakan.',
                ], 400);
            }

            // 2. CEK EXPIRY (15 menit)
            if (Carbon::now()->isAfter($qr_code->expired_at)) {
                return response()->json([
                    'success' => false,
                    'message' => 'QR Code sudah kadaluarsa. Minta Ketua Kelas generate QR baru.',
                ], 400);
            }

            // 3. VALIDASI JADWAL
            $jadwal = JadwalMengajar::with(['kelas', 'mataPelajaran'])
                ->find($qr_code->jadwal_id);

            if (!$jadwal) {
                return response()->json([
                    'success' => false,
                    'message' => 'Jadwal mengajar tidak ditemukan.',
                ], 404);
            }

            // 4. CEK APAKAH GURU INI SESUAI DENGAN JADWAL
            if ($jadwal->guru_id !== $guru->id) {
                return response()->json([
                    'success' => false,
                    'message' => 'QR Code ini bukan untuk jadwal Anda.',
                ], 403);
            }

            // 5. CEK APAKAH SUDAH ABSEN HARI INI
            $sudah_absen = Absensi::where('jadwal_id', $jadwal->id)
                ->whereDate('tanggal', Carbon::today())
                ->exists();

            if ($sudah_absen) {
                return response()->json([
                    'success' => false,
                    'message' => 'Anda sudah melakukan absensi untuk jadwal ini hari ini.',
                ], 400);
            }

            // 6. VALIDASI GPS
            $jarak = $this->calculateDistance(
                $request->latitude,
                $request->longitude,
                self::SEKOLAH_LAT,
                self::SEKOLAH_LNG
            );

            if ($jarak > self::RADIUS_METER) {
                return response()->json([
                    'success' => false,
                    'message' => "Lokasi Anda terlalu jauh dari sekolah (" . round($jarak) . "m). Maksimal " . self::RADIUS_METER . "m.",
                ], 400);
            }

            // 7. TENTUKAN STATUS (hadir atau terlambat)
            $jam_sekarang = Carbon::now();
            $jam_mulai = Carbon::createFromFormat('H:i:s', $jadwal->jam_mulai);
            $toleransi_terlambat = 15; // menit

            $status = 'hadir';
            $keterangan = null;
            if ($jam_sekarang->greaterThan($jam_mulai->copy()->addMinutes($toleransi_terlambat))) {
                $status = 'terlambat';
                $menit_terlambat = $jam_sekarang->diffInMinutes($jam_mulai);
                $keterangan = "Terlambat {$menit_terlambat} menit";
            }

            // 8. SIMPAN ABSENSI
            $absensi = Absensi::create([
                'jadwal_id' => $jadwal->id,
                'tanggal' => Carbon::today(),
                'jam_absen' => Carbon::now()->format('H:i:s'),
                'status' => $status,
                'metode_absensi' => 'qr_code',
                'latitude' => $request->latitude,
                'longitude' => $request->longitude,
                'jarak_meter' => round($jarak, 2),
                'validasi_guru_piket' => true,  // QR otomatis valid
                'keterangan' => $keterangan ?? "Scan QR dari Ketua Kelas {$jadwal->kelas->nama_kelas}",
            ]);

            // 9. TANDAI QR CODE SEBAGAI SUDAH DIGUNAKAN
            $qr_code->update([
                'is_used' => true,
                'used_by_guru_id' => $guru->id,
                'used_at' => Carbon::now(),
            ]);

            return response()->json([
                'success' => true,
                'message' => "Absensi berhasil! Status: " . strtoupper($status),
                'data' => [
                    'absensi_id' => $absensi->id,
                    'status' => $status,
                    'status_text' => $status === 'hadir' ? 'Hadir' : 'Terlambat',
                    'jam_absen' => $absensi->jam_absen,
                    'kelas' => $jadwal->kelas->nama_kelas,
                    'mata_pelajaran' => $jadwal->mataPelajaran->nama_mapel,
                    'jarak_meter' => round($jarak, 2),
                    'keterangan' => $keterangan,
                ],
            ]);

        } catch (\Illuminate\Validation\ValidationException $e) {
            return response()->json([
                'success' => false,
                'message' => 'Validasi gagal.',
                'errors' => $e->errors(),
            ], 422);
        } catch (\Exception $e) {
            \Log::error('Error proses absensi QR: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan: ' . $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Proses Absensi via Selfie
     * Selfie akan di-validasi oleh Ketua Kelas
     */
    public function prosesAbsensiSelfie(Request $request)
    {
        $request->validate([
            'jadwal_id' => 'required|exists:jadwal_mengajar,id',
            'foto_selfie' => 'required|string', // Base64 encoded image
            'latitude' => 'required|numeric',
            'longitude' => 'required|numeric',
        ]);

        try {
            $user = Auth::user();
            $guru = $user->guru;

            if (!$guru) {
                return response()->json([
                    'success' => false,
                    'message' => 'Data guru tidak ditemukan.',
                ], 404);
            }

            // 1. VALIDASI JADWAL
            $jadwal = JadwalMengajar::with(['kelas', 'mataPelajaran'])->find($request->jadwal_id);

            if (!$jadwal) {
                return response()->json([
                    'success' => false,
                    'message' => 'Jadwal tidak ditemukan.',
                ], 404);
            }

            // 2. CEK APAKAH GURU INI SESUAI DENGAN JADWAL
            if ($jadwal->guru_id !== $guru->id) {
                return response()->json([
                    'success' => false,
                    'message' => 'Jadwal ini bukan milik Anda.',
                ], 403);
            }

            // 3. CEK APAKAH SUDAH ABSEN HARI INI
            $sudah_absen = Absensi::where('jadwal_id', $jadwal->id)
                ->whereDate('tanggal', Carbon::today())
                ->exists();

            if ($sudah_absen) {
                return response()->json([
                    'success' => false,
                    'message' => 'Anda sudah melakukan absensi untuk jadwal ini hari ini.',
                ], 400);
            }

            // 4. VALIDASI GPS
            $jarak = $this->calculateDistance(
                $request->latitude,
                $request->longitude,
                self::SEKOLAH_LAT,
                self::SEKOLAH_LNG
            );

            if ($jarak > self::RADIUS_METER) {
                return response()->json([
                    'success' => false,
                    'message' => 'Lokasi Anda terlalu jauh dari sekolah (' . round($jarak) . 'm). Maksimal ' . self::RADIUS_METER . 'm.',
                ], 400);
            }

            // 5. SIMPAN FOTO SELFIE
            $foto_path = $this->saveSelfie($request->foto_selfie, $guru->id);

            if (!$foto_path) {
                return response()->json([
                    'success' => false,
                    'message' => 'Gagal menyimpan foto selfie.',
                ], 500);
            }

            // 6. TENTUKAN STATUS (hadir atau terlambat)
            $jam_sekarang = Carbon::now();
            $jam_mulai = Carbon::createFromFormat('H:i:s', $jadwal->jam_mulai);
            $toleransi_terlambat = 15; // menit

            $status = 'hadir';
            $keterangan = 'Menunggu validasi Ketua Kelas';
            if ($jam_sekarang->greaterThan($jam_mulai->copy()->addMinutes($toleransi_terlambat))) {
                $status = 'terlambat';
                $menit_terlambat = $jam_sekarang->diffInMinutes($jam_mulai);
                $keterangan = "Terlambat {$menit_terlambat} menit - Menunggu validasi Ketua Kelas";
            }

            // 7. DAPATKAN KETUA KELAS
            $kelas = $jadwal->kelas;
            $ketua_kelas_user_id = $kelas->ketua_kelas_user_id ?? null;

            // 8. SIMPAN ABSENSI (Status Pending Validation)
            $absensi = Absensi::create([
                'jadwal_id' => $jadwal->id,
                'tanggal' => Carbon::today(),
                'jam_absen' => Carbon::now()->format('H:i:s'),
                'status' => $status,
                'metode_absensi' => 'selfie',
                'latitude' => $request->latitude,
                'longitude' => $request->longitude,
                'jarak_meter' => round($jarak, 2),
                'foto_selfie' => $foto_path,
                'validasi_ketua_kelas' => false,  // Pending validation
                'validasi_oleh_ketua_kelas_id' => $ketua_kelas_user_id,
                'keterangan' => $keterangan,
            ]);

            return response()->json([
                'success' => true,
                'message' => 'Selfie berhasil dikirim! Menunggu validasi Ketua Kelas.',
                'data' => [
                    'absensi_id' => $absensi->id,
                    'status' => $status,
                    'status_text' => $status === 'hadir' ? 'Hadir (Pending)' : 'Terlambat (Pending)',
                    'jam_absen' => $absensi->jam_absen,
                    'kelas' => $jadwal->kelas->nama_kelas,
                    'mata_pelajaran' => $jadwal->mataPelajaran->nama_mapel,
                    'jarak_meter' => round($jarak, 2),
                    'validasi_ketua_kelas' => false,
                    'pesan' => 'Absensi Anda menunggu validasi dari Ketua Kelas ' . $jadwal->kelas->nama_kelas,
                ],
            ]);

        } catch (\Exception $e) {
            \Log::error('Error proses absensi selfie: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Terjadi kesalahan: ' . $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Riwayat Absensi Guru
     */
    public function riwayat(Request $request)
    {
        $user = Auth::user();
        $guru = $user->guru;

        if (!$guru) {
            return redirect()->route('guru.dashboard')
                ->with('error', 'Data guru tidak ditemukan.');
        }

        // Jika AJAX request, return JSON
        if ($request->wantsJson() || $request->ajax()) {
            $riwayat = Absensi::with(['jadwal.kelas', 'jadwal.mataPelajaran'])
                ->whereHas('jadwal', function($q) use ($guru) {
                    $q->where('guru_id', $guru->id);
                })
                ->whereDate('tanggal', Carbon::today())
                ->orderBy('jam_absen', 'asc')
                ->get();

            return response()->json([
                'success' => true,
                'data' => $riwayat->map(function($item) {
                    return [
                        'id' => $item->id,
                        'jam_absen' => $item->jam_absen ? Carbon::parse($item->jam_absen)->format('H:i') : '-',
                        'status' => $item->status,
                        'status_text' => ucfirst($item->status),
                        'metode_absensi' => $item->metode_absensi,
                        'keterangan' => $item->keterangan,
                        'validasi_ketua_kelas' => $item->validasi_ketua_kelas ?? null,
                        'kelas' => $item->jadwal->kelas->nama_kelas ?? '-',
                        'mata_pelajaran' => $item->jadwal->mataPelajaran->nama_mapel ?? '-',
                    ];
                }),
            ]);
        }

        // View untuk HTML
        $riwayat = Absensi::with(['jadwal.kelas', 'jadwal.mataPelajaran'])
            ->whereHas('jadwal', function($q) use ($guru) {
                $q->where('guru_id', $guru->id);
            })
            ->whereDate('tanggal', Carbon::today())
            ->orderBy('jam_absen', 'asc')
            ->get();

        return view('guru.absensi.riwayat', [
            'guru' => $guru,
            'riwayat' => $riwayat,
        ]);
    }

    /**
     * Hitung Jarak GPS (Haversine Formula)
     */
    private function calculateDistance($lat1, $lon1, $lat2, $lon2)
    {
        $earthRadius = 6371000; // meter

        $latFrom = deg2rad($lat1);
        $lonFrom = deg2rad($lon1);
        $latTo = deg2rad($lat2);
        $lonTo = deg2rad($lon2);

        $latDelta = $latTo - $latFrom;
        $lonDelta = $lonTo - $lonFrom;

        $a = sin($latDelta / 2) * sin($latDelta / 2) +
             cos($latFrom) * cos($latTo) *
             sin($lonDelta / 2) * sin($lonDelta / 2);
        $c = 2 * atan2(sqrt($a), sqrt(1 - $a));

        return $earthRadius * $c; // Jarak dalam meter
    }

    /**
     * Simpan Foto Selfie
     */
    private function saveSelfie($base64Image, $guruId)
    {
        try {
            // Hapus prefix data:image/...;base64,
            $image = preg_replace('/^data:image\/\w+;base64,/', '', $base64Image);
            $image = str_replace(' ', '+', $image);

            // Decode base64
            $imageData = base64_decode($image);

            if ($imageData === false) {
                throw new \Exception('Invalid base64 image data');
            }

            // Generate filename
            $filename = 'selfie_' . $guruId . '_' . time() . '.jpg';
            $directory = storage_path('app/public/selfie');

            // Buat folder jika belum ada
            if (!file_exists($directory)) {
                mkdir($directory, 0755, true);
            }

            // Simpan file
            $path = $directory . '/' . $filename;
            file_put_contents($path, $imageData);

            return 'selfie/' . $filename;

        } catch (\Exception $e) {
            \Log::error('Error saving selfie: ' . $e->getMessage());
            return null;
        }
    }
}
